// GENERATED by scripts/gen-ward-bboxes.mjs — do not edit by hand.
// Layer-level bounding boxes [west, south, east, north] for every wards_* layer,
// read from each layer's PMTiles header (tight, city-scale). The locate endpoint
// point-tests these to auto-include the ward layer(s) covering a query point.
// Regenerate after adding/removing/replacing a ward layer:
//     node scripts/gen-ward-bboxes.mjs
export type WardBbox = [west: number, south: number, east: number, north: number];

export const WARD_BBOXES: Record<string, WardBbox> = {
  "wards_ahmedabad": [72.447243, 22.912141, 72.703695, 23.138648],
  "wards_bengaluru_bbmp_2022": [77.45988, 12.83349, 77.784361, 13.14262],
  "wards_bengaluru_gba": [77.45988, 12.83349, 77.784064, 13.14262],
  "wards_bhopal": [77.260416, 23.110891, 77.535781, 23.339225],
  "wards_bhubaneshwar": [85.753294, 20.211271, 85.903399, 20.366401],
  "wards_chandigarh": [76.704985, 30.664942, 76.849028, 30.794953],
  "wards_chennai": [80.134095, 12.852093, 80.331494, 13.235049],
  "wards_coimbatore": [76.868591, 10.91443, 77.065781, 11.103539],
  "wards_delhi": [76.838772, 28.404252, 77.34747, 28.883496],
  "wards_faridabad": [77.215181, 28.296277, 77.362593, 28.512301],
  "wards_gurugram": [76.928215, 28.369233, 77.165793, 28.531763],
  "wards_guwahati": [91.634689, 26.084219, 91.852144, 26.209287],
  "wards_hyderabad": [78.271751, 17.291638, 78.62123, 17.560832],
  "wards_indore": [75.769584, 22.625993, 75.98616, 22.820899],
  "wards_jaipur": [75.68751, 26.772871, 75.910024, 27.029771],
  "wards_kanpur": [80.198229, 26.334967, 80.473479, 26.533408],
  "wards_kochi": [76.237067, 9.893081, 76.339904, 10.050266],
  "wards_kolkata": [88.242143, 22.450323, 88.458955, 22.632577],
  "wards_lucknow": [80.831116, 26.744079, 81.060932, 26.934364],
  "wards_madurai": [78.048268, 9.831651, 78.194309, 9.988863],
  "wards_mumbai": [72.776333, 18.893956, 72.980645, 19.270177],
  "wards_mysuru": [76.598409, 12.253216, 76.70565, 12.355029],
  "wards_navi_mumbai": [72.96885, 18.988819, 73.050117, 19.191978],
  "wards_patna": [85.053456, 25.556492, 85.266005, 25.6511],
  "wards_pcmc": [73.710425, 18.563864, 73.933979, 18.721132],
  "wards_pune": [73.73193, 18.38539, 74.01838, 18.62185],
  "wards_surat": [72.701463, 21.055728, 72.968665, 21.318639],
  "wards_thane": [72.910385, 19.129359, 73.075894, 19.299907],
  "wards_vadodara": [73.113592, 22.215078, 73.269622, 22.381328],
  "wards_vijayawada": [80.586658, 16.47866, 80.684366, 16.584445],
  "wards_vizag": [82.994407, 17.546475, 83.463702, 17.940439],
};
